---
# GitHub Release Notes Configuration
# This file configures how GitHub auto-generates release notes
# It separates dependency updates into a "Version Bumps" section
# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - dependencies
  categories:
    - title: Version Bumps
      labels:
        - dependencies
