---
# GitHub Release Notes Configuration
# This file configures how GitHub auto-generates release notes
# It separates dependency updates into a "Version Bumps" section
# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  categories:
    - title: 🚀 New Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
    - title: 📚 Documentation
      labels:
        - documentation
        - docs
    - title: 🔧 Maintenance
      labels:
        - maintenance
        - chore
        - refactor
    - title: 📦 Version Bumps
      labels:
        - dependencies
