---
apiVersion: v1
kind: Namespace
metadata:
  name: netbox-operator-system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: netbox-operator
    app.kubernetes.io/part-of: netbox-operator
    app.kubernetes.io/managed-by: kustomize
