---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: netbox-operator-system
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: "RECONCILE_SCHEDULE"
              value: "50 5 * * *" # if no schedule is defined scheduled reconciliation is disabled
            - name: "RECONCILE_JITTER"
              value: "10m" # defaults to 1h if empty
