---
resources:
  - load-data-job.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: ghcr.io/zalando/spilo-16
    newName: ghcr.io/zalando/spilo-16
patches:
  - path: sql-env-patch.yaml
