apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: metallb-ip-address-pool-from-netbox-parent-prefix
spec:
  schema:
    apiVersion: v1alpha1
    kind: MetalLBIPAddressPoolFromNetBoxParentPrefix
    spec:
      name: string
      tenant: string
      site: string
      description: string
      comments: string
      preserveInNetbox: boolean
      prefixLength: string
      parentPrefix: string
    status:

  # Define the resources this API will manage.
  resources:
    - id: prefixclaim
      template:
        apiVersion: netbox.dev/v1
        kind: PrefixClaim
        metadata:
          name: ${schema.spec.name} # Use the name provided by user
        spec:
          tenant: ${schema.spec.tenant}
          description: ${schema.spec.description}
          comments: ${schema.spec.comments}
          preserveInNetbox: ${schema.spec.preserveInNetbox}
          parentPrefix: ${schema.spec.parentPrefix}
          prefixLength: ${schema.spec.prefixLength}

    - id: ipaddresspool
      template:
        apiVersion: metallb.io/v1beta1
        kind: IPAddressPool
        metadata:
          name: ${schema.spec.name}
          namespace: metallb-system
        spec:
          addresses:
            - ${prefixclaim.status.prefix}
