# permissions for end users to view ipaddressclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ipaddressclaim-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: netbox-operator
    app.kubernetes.io/part-of: netbox-operator
    app.kubernetes.io/managed-by: kustomize
  name: ipaddressclaim-viewer-role
rules:
- apiGroups:
  - netbox.dev
  resources:
  - ipaddressclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netbox.dev
  resources:
  - ipaddressclaims/status
  verbs:
  - get
