# permissions for end users to edit ipranges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: iprange-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: netbox-operator
    app.kubernetes.io/part-of: netbox-operator
    app.kubernetes.io/managed-by: kustomize
  name: iprange-editor-role
rules:
- apiGroups:
  - netbox.dev
  resources:
  - ipranges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netbox.dev
  resources:
  - ipranges/status
  verbs:
  - get
