# permissions for end users to view prefixes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: netbox-operator
    app.kubernetes.io/managed-by: kustomize
  name: prefix-viewer-role
rules:
- apiGroups:
  - ipam.netboxlabs.com
  resources:
  - prefixes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ipam.netboxlabs.com
  resources:
  - prefixes/status
  verbs:
  - get
