---

apiVersion: v1
kind: Service
metadata:
  name: netbox
  namespace: default
  annotations:
    metallb.universe.tf/address-pool: netbox-ipaddresspool
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/component: netbox
    app.kubernetes.io/instance: netbox
    app.kubernetes.io/name: netbox
  sessionAffinity: None
