apiVersion: netbox.dev/v1
kind: IpRangeClaim
metadata:
  labels:
    app.kubernetes.io/name: netbox-operator
    app.kubernetes.io/managed-by: kustomize
  name: iprangeclaim-sample
spec:
  # TODO(user): Add fields here
