apiVersion: netbox.dev/v1
kind: L2VPNClaim
metadata:
  labels:
    app.kubernetes.io/name: netbox-operator
    app.kubernetes.io/managed-by: kustomize
  name: l2vpnclaim-range-sample
spec:
  tenant: "Dunder-Mifflin, Inc."
  description: "some description"
  comments: "your comments"
  preserveInNetbox: true
  type: "vxlan-evpn"
  identifierRangeStart: 4000
  identifierRangeEnd: 16777215
