apiVersion: netbox.dev/v1
kind: PrefixClaim
metadata:
  labels:
    app.kubernetes.io/name: netbox-operator
    app.kubernetes.io/managed-by: kustomize
  name: prefixclaim-parentprefixselector-sample
spec:
  tenant: "MY_TENANT" # Use the `name` value instead of the `slug` value
  site: "DM-Akron" # Use the `name` value instead of the `slug` value
  description: "some description"
  comments: "your comments"
  preserveInNetbox: true
  prefixLength: "/31"
  parentPrefixSelector: # The keys and values are case-sensitive
    # if the entry for tenant or site is missing, it will *not* inherit from the tenant and site from the Spec
    tenant: "MY_TENANT" # Use the `name` value instead of the `slug` value
    site: "DM-Buffalo" # Use the `name` value instead of the `slug` value
    
    # custom fields of your interest
    environment: "Production"
    poolName: "Pool 1"
    # environment: "production"
    # poolName: "pool 3"
