---
apiVersion: netbox.dev/v1
kind: IpRangeClaim
metadata:
  labels:
    app.kubernetes.io/name: netbox-operator
    app.kubernetes.io/managed-by: kustomize
  name: iprangeclaim-sample
spec:
  tenant: "Dunder-Mifflin, Inc."
  description: "some description"
  comments: "your comments"
  preserveInNetbox: true
  parentPrefix: "2.0.0.0/16"
  size: 3
