---
apiVersion: netbox.dev/v1
kind: PrefixClaim
metadata:
  labels:
    app.kubernetes.io/name: netbox-operator
    app.kubernetes.io/managed-by: kustomize
  name: prefixclaim-parentprefixselector-bool-int-sample
spec:
  tenant: "MY_TENANT"
  site: "DM-Akron"
  description: "some description"
  comments: "your comments"
  preserveInNetbox: true
  prefixLength: "/31"
  parentPrefixSelector:
    # should return a prefix in 3.0.0.0/24 with the sample data
    environment: "Production"
    poolName: "Pool 1"
    cfDataTypeBool: "true"
    cfDataTypeInteger: "1"
