apiVersion: kro.run/v1alpha1
kind: MetalLBIPAddressPoolFromNetBoxParentPrefix
metadata:
  name: podinfo-test
spec:
  name: podinfo-test
  tenant: "MY_TENANT" # Use the `name` value instead of the `slug` value
  preserveInNetbox: true
  prefixLength: "/30"
  parentPrefix: 3.0.0.64/26