version: "2"
linters:
  default: none
  enable:
    - goheader
    - ineffassign
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    goheader:
      values:
        regexp:
          AUTHOR: ^Copyright 2024 (The Kubernetes authors|Swisscom \(Schweiz\) AG)\.
      template: |-
        {{ AUTHOR }}

        Licensed under the Apache License, Version 2.0 (the "License");
        you may not use this file except in compliance with the License.
        You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.
    revive:
      confidence: 0.8
      severity: error
      enable-all-rules: false
      rules:
        - name: blank-imports
          severity: error
          disabled: false
        - name: context-as-argument
          severity: error
          disabled: false
        - name: dot-imports
          severity: error
          disabled: true
        - name: error-return
          severity: error
          disabled: false
        - name: error-naming
          severity: error
          disabled: false
        - name: if-return
          severity: error
          disabled: false
        - name: increment-decrement
          severity: error
          disabled: false
        - name: var-declaration
          severity: error
          disabled: false
        - name: package-comments
          severity: error
          disabled: false
        - name: range
          severity: error
          disabled: false
        - name: receiver-naming
          severity: error
          disabled: false
        - name: time-naming
          severity: error
          disabled: false
        - name: indent-error-flow
          severity: error
          disabled: false
        - name: errorf
          severity: error
          disabled: false
        - name: context-keys-type
          severity: error
          disabled: false
        - name: error-strings
          severity: error
          disabled: false
    staticcheck:
      checks:
        - -SA1019
        - -SA2002
        - ST1019
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - ^zz_generated.*
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - ^zz_generated.*
      - third_party$
      - builtin$
      - examples$
