---
name: Integration Tests
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    tags:
      - v*
  workflow_run:
    workflows: ["Release"]
    types: [completed]
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v5.0.0
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "go.mod"
      - name: tests
        run: |-
          go install github.com/onsi/ginkgo/v2/ginkgo
          make integration-test
