---
name: Static analysis
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    tags:
      - v*
  workflow_run:
    workflows: ["Release"]
    types: [completed]
    branches: [main]
  pull_request:
permissions: read-all
jobs:
  go-and-crds:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v5.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "go.mod"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          version: v2.11.2
          args: --config tools/.golangci.yaml
      - run: |
          set -euo pipefail

          make vet
      - run: |
          set -euo pipefail

          make lint
      - run: |
          set -euo pipefail

          make fmt

          DIFF=$(git status --porcelain)

          if [ -n "$DIFF" ]; then
            echo "These files were modified:"
            echo
            echo "$DIFF"
            echo
            exit 1
          fi
      - run: |
          set -euo pipefail

          DIFF=$(git status --porcelain)

          make generate manifests

          if [ -n "$DIFF" ]; then
          echo "These files were modified:"
          echo
          echo "$DIFF"
          echo
          echo "Please run make generate manifests and commit the changes."
          exit 1
          fi
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v5.0.0
      - name: Run codespell
        uses: codespell-project/actions-codespell@v2
        with:
          skip: "*.svg"
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v5.0.0
      - name: "Yamllint"
        uses: karancode/yamllint-github-action@master
